### ISSUE TITLE
Implement a form of `try ... catch`

### ISSUE THREAD

**Issue by sampersand** [sampersand/quest#16]
Currently, exceptions are just thrown all the way to the outermost layer (except for `Return`). 

They should be accessible from within quest, and be catchable. This shouldn't be too hard to do.

# Roadmap
- [ ] Make `quest_core::Error` a `ObjectType` and implement basic methods
- [ ] Make each of the error derivatives (eg `KeyError`) also a `ObjectType`
- [ ] Have a way to catch errors (e.g. a function called `catch`)
	- [ ] To keep things simple now, we might just want to have it take two blocks, the first is what to execute, the second is the rescue block
	- [ ] Have a way to distinguish between errors (eg #14)
- [ ] Have a way to throw errors (e.g. a function called `throw`)
	- [ ] Should we be able to throw any arbitrary object, or _must_ they be an error type?
	- [ ] Should we hijack `return` and instead do `return(KeyError("err"))` and have the `catch` block try catching `KeyError`s?
