### ISSUE TITLE
Add Unit and E2E tests

### ISSUE THREAD

**Issue by sampersand** [sampersand/quest#30]
Both of these are crucial for further development, and should be done by no later than alpha.

# Roadmap

## Quest Core
- [ ] Unit tests
	- [ ] "Core" objects
	- [ ] Helper objects
	- [ ] Other things
- [ ] E2E Testing
	- [ ] Ensure the `Object:*_attr` family of functions all work correctly
	- [ ] <find more stuff to include?>

## Quest Parser
- [ ] Unit Tests
	- [ ] Stream-to-token unit testing
		- [ ] Primaries
		- [ ] Parens
		- [ ] Tokens overall
	- [ ] Token-to-expression unit testing
		- [ ] Primaries map correctly
		- [ ] Blocks are parsed correctly
- [ ] E2E Testing
	- [ ] ??

## Quest Bin
- [ ] Unit Tests
	- [ ] Command-line argument parsing
	- [ ] ??
- [ ] E2E Testing
	- [ ] ??

## E2E Overall
- [ ] Write some test files and ensure they're executed properly?
