### ISSUE TITLE
Changing `$...` syntax to be evaluating text

### ISSUE THREAD

**Issue by sampersand** [sampersand/quest#8]
Currently, variable literals are written as `varname`, whereas the `$...` syntax is another way to write out Text literals.

I propose we flip the two around, and have unquoted variable names be interpreted as text as well, and `$...` be reserved for variable literals. I thought originally it might be ok with the way I have it because BASH does it this way, but I realize now that basing language design off bash isn't the best idea 😛 

# Roadmap
- [x] Update the two literals within the parser
- [ ] Run the (few) tests I have :/
- [ ] Update example code

# Advantages

- Vastly removes visual clutter (reading/writing attributes is more common than evaluating them).
- Reduces confusion. It makes more sense to access attributes by their names, and not with a random sigil in front. (Plus, the intent is more obvious when you say `$memo.$n` than `memo.n`)

# Issues
- What to do with stack literals? should those be still `:#` or `$:#` now?
- We end up with somewhat-weird `$disp` syntax.
- We lose the advantage of `$+ = { ... }` and have to write `'+' = { ... }`

# Example
```quest
$Number.square = { _0 ** 2 };
$disp( 4.square() );

$Number.factorial = {
	memo = { :0 }();
	$memo.0 = 1;
	{
		if($memo.__has_attr__($_0), {
			$memo.$_0
		}, {
			$memo.$_0 = ($_0 - 1).factorial() * $_0
		})
	}
}();

$disp('5! =', 5.factorial());
$disp('10! = ', 10.factorial());
```

**Comment by sampersand** [comment]
It doesn't actually  remove visual clutter—it adds to it! but that depends on what program you're running. I'm going to talk with some people to see what they think of the newsystem, and figure out the best course of action to go from there.

**Comment by sampersand** [comment]
> It doesn't actually remove visual clutter—it adds to it! but that depends on what program you're running. I'm going to talk with some people to see what they think of the newsystem, and figure out the best course of action to go from there.

In fact, you read variables far more often than you write them... Hopefully the fact that `$` makes it clear variables are being executed makes up for the increased clutter

**Comment by sampersand** [comment]
In fact, here's what the two different syntaxes look like.

Before:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/6655027/86217054-74e23580-bb6e-11ea-93d4-0b2bf2094a7c.png">

After:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/6655027/86216989-5c721b00-bb6e-11ea-9e3c-87806e056aaf.png">

**Comment by sampersand** [comment]
I don't think this is going to work out. closing it.
